name: APK Building
# Run the workflow when commits are pushed on main or when a PR is modified
on:
  push:
    branches:
      - main
      - 71-self-sign-apk-to-fix-new-bug

permissions:
    contents: write
      
jobs:
    build:
      name: Build Release APK
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create file
        run: cat /home/runner/work/feedme-android/app/google-services.json | base64

      - name: Load Google Service file
        env:
            DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
            ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_FILE }}
            ENCODED_PASSWORDS: ${{ secrets.KEYSTORE_PASSWORDS }}
            
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/google-services.json
          echo $ENCODED_KEYSTORE | base64 -di > keystore.jks
          echo $ENCODED_PASSWORDS | base64 -di > keystore.properties
  
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
  
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Get release path
        id: feedmePath
        run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT

      - name: Upload APK in artifacts
        uses: actions/upload-artifact@v4
        with:
          name: feedme-apk
          path: ${{ steps.feedmePath.outputs.apkfile }}
          if-no-files-found: error
          retention-days: 90
          
      - name: Release APK
        uses: softprops/action-gh-release@v2
        with:
          name: FeedMe v1.x.x
          files: ${{ steps.feedmePath.outputs.apkfile }}
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
        
    